version: '3'
services:
  auth-app:
    build:
      context: ./auth-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
    env_file:
      - auth-app/.env
    depends_on:
      - mongodb

  post-app:
    build:
      context: ./post-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_URI=postgres://postgres:5432/mydatabase
    env_file:
      - post-app/.env
    depends_on:
      - postgres
      - auth-app

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - post-app/.env

volumes:
  mongo:
  postgres:
